feature: add annotation blocker plugin to bcs-webhook-server; issue #…
Tencent/bk-bcs pull request #1165
Opened 2021-12-14 13:52 UTC by abstractmj

…1164

2022-01-11 12:11 UTC, silenceper requested changes

2022-01-11 12:11 UTC, silenceper commented on bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/blockannotation/expr.go
> +package blockannotation
同上，缺失License信息

2022-01-25 02:26 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/blockannotation/conf.go
> +package blockannotation
fixed

2022-01-25 02:26 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/blockannotation/expr.go
> +			fmt.Printf("%v, %v", tmpV, v)
fixed

2022-01-25 02:26 UTC, abstractmj commented on bcs-runtime/bcs-k8s/bcs-component/bcs-webhook-server/internal/plugin/blockannotation/expr.go
> +package blockannotation
fixed

2022-01-25 02:38 UTC, silenceper commented
/LGTM

2022-01-25 12:29 UTC, wenxinlee2015 approved these changes

2022-01-25 12:30 UTC, wenxinlee2015 approved these changes

2022-01-25 12:31 UTC, wenxinlee2015 approved these changes

2022-01-25 12:42 UTC, wenxinlee2015 approved these changes

2022-01-25 12:42 UTC, silenceper approved these changes

2022-01-25 12:43 UTC, merged