feat：bcs-webconsole模块下沉到后台
Tencent/bk-bcs pull request #1191
Opened 2021-12-17 12:27 UTC by linfang-canway

golang重构原先 bcs-SaaS中webconsole模块

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/app/app.go
> +	op.Conf.DockerImage = "ccr.ccs.tencentyun.com/bk-cmdb-lf/bcs-webconsole:v0.1"
这里的镜像应该要么是变量， 要么在运维层解决

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/console/api/api.go
> +		fmt.Println(err)
提交了Println代码，这个本地测试OK， PR需要去掉

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/console/api/api.go
> +		fmt.Println(err)
提交了Println代码，这个本地测试OK， PR需要去掉

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/console/api/api.go
> +			"session_id": "666666",
同上， session_id变量需要处理下

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/console/manager/console.go
> +		fmt.Errorf("start exec failed for container %s: %s", conf.ContainerID, err.Error())
同上

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/console/manager/console.go
> +	"#######################################################################\r\n",
这个是console proxy返回的提示吧， web-console返回有自己的提示哦

2021-12-21 01:48 UTC, ifooth commented on bcs-services/bcs-webconsole/web/templates/index.html
> -            <h2>{{ _("连接已经断开") }}</h2>
这个国际化可先记录，后面再支持。

2021-12-21 01:55 UTC, linfang-canway commented on bcs-services/bcs-webconsole/web/templates/index.html
> -            <h2>{{ _("连接已经断开") }}</h2>
ok

2021-12-21 01:56 UTC, linfang-canway commented on bcs-services/bcs-webconsole/app/app.go
> +	op.Conf.DockerImage = "ccr.ccs.tencentyun.com/bk-cmdb-lf/bcs-webconsole:v0.1"
这个配置参数可以放到启动的配置文件中去吗？

2021-12-24 07:18 UTC, Lwxiang requested changes

2021-12-24 07:18 UTC, Lwxiang commented on bcs-services/bcs-webconsole/console/manager/console.go
> +			for _, i := range ConsoleCopywritingFailed {
这里拆成多个byte去WriteMessage的目的是什么？

2021-12-24 07:18 UTC, Lwxiang commented on bcs-services/bcs-webconsole/console/manager/console.go
> +	}
这里对`IsOneSession`的处理比较繁琐，锁处理比较分散，后续不好维护。

考虑对connectedContainers的操作封装一个接口，例如：
```golang
type connectionPool interface {
    TryHoldConnection(containerID string) bool
    ReleaseConnection(containerID string)
}

if m.conf.IsOneSession {
    // 在TryHoldConnection内部完成一次性的锁处理
    // 若拿的到就占住, 返回true; 拿不到就返回false
    if !m.connectionPool.TryHoldConnection(conf.ContainerID) {
        // TODO: write back failed message
        return
    }
    
    // 同样的在内部一次性处理锁, 不要把锁暴露给外部调用者
    defer m.connectionPool.ReleaseConnection(conf.ContainerID)
}
```

2021-12-24 07:18 UTC, Lwxiang commented on bcs-services/bcs-webconsole/console/manager/console.go
> +}
这里是测试代码么？测试内容不允许提交到主库里。

2022-01-11 07:16 UTC, linfang-canway commented on bcs-services/bcs-webconsole/app/app.go
> +	c.route = api.NewRouter(c.backend, c.conf)
get

2022-01-12 09:03 UTC, ifooth commented on bcs-services/bcs-webconsole/app/app.go
> +/*
这个等下个PR我这边处理

2022-01-12 09:03 UTC, ifooth approved these changes

2022-01-12 09:10 UTC, Lwxiang approved these changes
LGTM

2022-01-12 09:11 UTC, ifooth commented
LGTM

2022-01-12 09:12 UTC, merged