feature: add bcs monitor client
Tencent/bk-bcs pull request #1352
Opened 2022-02-13 16:24 UTC by kayinli

2022-02-14 13:08 UTC, DeveloperJim requested changes

2022-02-14 13:08 UTC, DeveloperJim commented on bcs-common/pkg/bcsmonitor/client.go
> +	CompleteEndpoint string
Opt、DefaultHeader、CompleteEndpoint不需要对外暴露

2022-02-14 13:08 UTC, DeveloperJim commented on bcs-common/pkg/bcsmonitor/client.go
> +func (c *BcsMonitorClient) doRequest(url, method string, header http.Header, data []byte) ([]byte, error) {
doRequest可以抽象实现的接口，方便我们test部分实现注入用于测试

2022-02-15 09:49 UTC, kayinli commented on bcs-common/pkg/bcsmonitor/client.go
> +	CompleteEndpoint string
已修改

2022-02-22 04:05 UTC, DeveloperJim approved these changes
LGTM

2022-02-22 04:07 UTC, merged