feature(GameWorkload): avoid cascading deletion with admission webhook
Tencent/bk-bcs pull request #1362
Opened 2022-02-16 08:49 UTC by xcming

- 防止用户误操作导致多服务不可用，使用 admission webhook 验证删除请求
- 删除 CRD 或 Workload 时进行验证
- 在 labels 中增加 `io.tencent.bcs.dev/deletion-allow` 以设置验证策略，支持以下三种验证策略：
  - Always: 总是允许删除操作
  - Cascading: 若有下属资源存活时，拒绝删除操作
  - 不存在对应 label 或为其他值时，总是拒绝删除操作

2022-04-18 03:04 UTC, DeveloperJim requested changes

2022-04-18 03:04 UTC, DeveloperJim commented on bcs-runtime/bcs-k8s/bcs-component/bcs-gamestatefulset-operator/cmd/gamestatefulset-operator/validator/server.go
> +// ServerRunOptions Server Run Options
应该和GameDeployment server设计复用

2022-04-18 03:04 UTC, DeveloperJim commented on bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/cmd/hook-operator/validator/server.go
> +type ServerRunOptions struct {
清理冗余设计

2022-05-09 07:15 UTC, xcming commented on bcs-runtime/bcs-k8s/bcs-component/bcs-hook-operator/cmd/hook-operator/validator/server.go
> +type ServerRunOptions struct {
已统一迁移至 kubernetes/common 目录下

2022-05-13 06:55 UTC, DeveloperJim approved these changes
LGTM

2022-05-13 07:00 UTC, merged