feature: change cluster remain resource calc, exclude disabled agent
Tencent/bk-bcs pull request #1428
Opened 2022-03-03 06:31 UTC by penglongli

修改 Mesos 集群 Cluster 剩余资源计算方式，排除 disable 节点

2022-03-07 07:55 UTC, penglongli commented
```
# 1. 集群节点 enable，指标 available 与 remain 相同
$ bcs-client offer list --clusterid BCS-MESOS-10000
INDEX  IP                 Hostname              CPUS  MEM       DISK       CITY       IPRESOURCES  PORTS
1      1.1.1.1        1.1.1.1           7.73  14541.00  196144.00             1            31000-32000
$ curl http://1.1.1.1:10000/metrics -s | grep cluster_cpu_resource
# HELP bkbcs_scheduler_cluster_cpu_resource_available Cluster cpu resource available
# TYPE bkbcs_scheduler_cluster_cpu_resource_available gauge
bkbcs_scheduler_cluster_cpu_resource_available{cloudId="BCS-MESOS-10000"} 7.7
# HELP bkbcs_scheduler_cluster_cpu_resource_remain Cluster cpu resource remain
# TYPE bkbcs_scheduler_cluster_cpu_resource_remain gauge
bkbcs_scheduler_cluster_cpu_resource_remain{clusterId="BCS-MESOS-10000"} 7.7
# HELP bkbcs_scheduler_cluster_cpu_resource_total Cluster cpu resource total
# TYPE bkbcs_scheduler_cluster_cpu_resource_total gauge
bkbcs_scheduler_cluster_cpu_resource_total{clusterId="BCS-MESOS-10000"} 8

# 2. 集群节点 disable，指标 available 变成了 0
$ bcs-client disable -t agent --ip  1.1.1.1 --clusterid BCS-MESOS-10000
success to disable agent
$ curl http://1.1.1.1:10000/metrics -s | grep cluster_cpu_resource
# HELP bkbcs_scheduler_cluster_cpu_resource_available Cluster cpu resource available
# TYPE bkbcs_scheduler_cluster_cpu_resource_available gauge
bkbcs_scheduler_cluster_cpu_resource_available{cloudId="BCS-MESOS-10000"} 0
# HELP bkbcs_scheduler_cluster_cpu_resource_remain Cluster cpu resource remain
# TYPE bkbcs_scheduler_cluster_cpu_resource_remain gauge
bkbcs_scheduler_cluster_cpu_resource_remain{clusterId="BCS-MESOS-10000"} 7.7
# HELP bkbcs_scheduler_cluster_cpu_resource_total Cluster cpu resource total
# TYPE bkbcs_scheduler_cluster_cpu_resource_total gauge
bkbcs_scheduler_cluster_cpu_resource_total{clusterId="BCS-MESOS-10000"} 8
```

2022-03-08 07:04 UTC, penglongli commented
@DeveloperJim 帮忙 Review 下这个 PR

2022-03-09 08:20 UTC, DeveloperJim requested changes

2022-03-09 08:20 UTC, DeveloperJim commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
> +		if err != nil {
补充异常处理

2022-03-09 08:20 UTC, DeveloperJim commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/zk/store.go
> +		}
补充异常处理

2022-03-09 08:20 UTC, DeveloperJim commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
> +				// no need to add remain cpu/mem if agent is disabled
计算方式和zookeeper不一致？

2022-03-09 08:47 UTC, penglongli commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
> +		if err != nil {
这个不需要处理的，这项指标如果拿失败，可以继续下边逻辑

2022-03-09 08:47 UTC, penglongli commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/zk/store.go
> +		}
这个不需要处理的，这项指标如果拿失败，可以继续下边逻辑

2022-03-09 08:48 UTC, penglongli commented on bcs-runtime/bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
> +				// no need to add remain cpu/mem if agent is disabled
etcd 的计算原本就没有 deltaCPU/deltaMemory，所以 available 只是在基础上加了 if 判断，不影响原本逻辑

2022-03-10 07:42 UTC, DeveloperJim approved these changes
LGTM

2022-03-10 07:42 UTC, merged