feat: bcs-argocd-server
Tencent/bk-bcs pull request #1520
Opened 2022-03-21 09:34 UTC by AlkaidChan

2022-03-21 12:08 UTC, Lwxiang requested changes
其他看起来没什么问题，把import调整一下就可以

2022-03-22 02:47 UTC, kayinli commented on bcs-services/bcs-argocd-manager/bcs-argocd-server/main.go
> +
可以加上 defer blog.CloseLogs()

2022-03-22 02:49 UTC, Lwxiang approved these changes

2022-03-22 02:54 UTC, merged

2022-03-22 04:46 UTC, AlkaidChan commented on bcs-services/bcs-argocd-manager/bcs-argocd-server/main.go
> +
在 server.go:104 有 close