feature: add bcs-data-manager #1631
Tencent/bk-bcs pull request #1632
Opened 2022-04-16 10:01 UTC by kayinli

add bcs-data-manager

2022-04-18 09:37 UTC, DeveloperJim requested changes

2022-04-18 09:37 UTC, DeveloperJim commented on bcs-services/bcs-data-manager/pkg/datajob/workload.go
> +		MaxCPUUsageTime:    minuteMetrics[len(minuteMetrics)-1].MaxCPUUsageTime,
优化写法

2022-04-18 09:37 UTC, DeveloperJim commented on bcs-services/bcs-data-manager/pkg/datajob/workload.go
> +		MaxCPUUsageTime:    hourMetrics[len(hourMetrics)-1].MaxCPUUsageTime,
优化写法

2022-04-18 09:37 UTC, DeveloperJim commented on bcs-services/bcs-data-manager/pkg/bcsmonitor/client.go
> +	err = json.Unmarshal(rsp, &result)
指针修正

2022-04-28 13:07 UTC, tencent-adm commented
[![CLA assistant check](https://cla.opensource.tencent.com/pull/badge/not_signed)](https://cla.opensource.tencent.com/Tencent/bk-bcs?pullRequest=1632) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-bcs?pullRequest=1632) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-bcs?pullRequest=1632) it.</sub>

2022-05-07 10:42 UTC, DeveloperJim requested changes

2022-05-07 10:42 UTC, DeveloperJim commented on bcs-services/bcs-data-manager/pkg/client/pkg/client_test.go
> +	rsp, err := client.GetClusterInfo(&datamanager.GetClusterInfoRequest{
测试不存在实际意义？

2022-05-09 06:39 UTC, merged